version: "3.7"
services:

  database:
    image: mysql:8.0.17
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - chemu-mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

volumes:
  chemu-mysql:
