version: "3.7"
services:

  database:
    image: mysql:8.0.17
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - chemu-mysql:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
    command: 'npm run start:dev'
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    links:
      - database

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
    command: 'npm run serve'
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    links:
      - backend

volumes:
  chemu-mysql:
